version: '3'

services:
  devault_api:
    build: .
    container_name: devault_api
    command: sh -c 'yarn prisma migrate deploy && yarn prisma generate && yarn start:dev'
    ports:
      - '3333:3333'
      - '5555:5555'
    volumes:
      - .:/usr/app/devault
    links:
      - db
    depends_on:
      - db

  db:
    container_name: devault-db
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=devault
      - POSTGRES_PASSWORD=devaultdocker
      - POSTGRES_DB=devault
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
