version: '3.7'

services:
  devault_api:
    build: .
    container_name: devault_api
    command:
      [
        'sh',
        '-c',
        'npm i && npx prisma migrate deploy && npx prisma generate && npx prisma db push && npm run start:dev',
      ]
    ports:
      - '4000:4000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - TOKEN_SECRET=${TOKEN_SECRET}
    volumes:
      - .:/usr/app/devault
    links:
      - db
    depends_on:
      - db

  prisma-studio:
    container_name: prisma-studio
    image: timothyjmiller/prisma-studio:latest
    restart: always
    environment:
      - POSTGRES_URL=${DATABASE_URL}
    ports:
      - 5555:5555
    links:
      - db
      - devault_api
    depends_on:
      - db
      - devault_api

  db:
    container_name: devault-db
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=devault
      - POSTGRES_PASSWORD=devaultdocker
      - POSTGRES_DB=devault
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
